const TILE_OPTIONS =  {
  updateWhenIdle: true,
  updateInterval: 10,
  tms: true
};

export const confessions = [
  {
    "name": "1. Karl Marx (Jennys Vater)",
    "baseUrl": "01_Karl_Marx_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Einfachheit"],
      ["… beim Mann", "Kraft"],
      ["… bei der Frau", "Schwäche"],
      ["Hauptmerkmal", "Zielstrebigkeit"],
      ["Auffassung vom Glück", ""],
      ["… vom Unglück", ""],
      ["Das Laster, das Du entschuldigst", "Leichtgläubigkeit"],
      ["… verabscheust", "Kriecherei"],
      ["Abneigung", "Martin Tupper [englischer Schriftsteller], Veilchenpuder"],
      ["Lieblingsbeschäftigung",
      "In Büchern stöbern [im ursprünglichen Entwurf: Nettchen (= Nanette Philips) anschauen]"],
      ["… Dichter", "Dante, Aeschylus, Shakespeare, Goethe"],
      ["… Schriftsteller", "Diderot, Lessing, Hegel, Bal[zac]"],
      ["… Held", "Spartacus, Keppler [deutscher Astronom]"],
      ["… Heldin", "Gretchen"],
      ["… Blume", "Seidelbast"],
      ["… Farbe", "Rot"],
      ["Augen- und Haarfarbe", "Schwarz"],
      ["… Namen", "Jenny, Laura"],
      ["… Essen", "Fisch"],
      ["Die historischen Persönlichkeiten, die Du am wenigsten magst", "[Frage nicht beantwortet]"],
      ["… Maxime", "Nihil humani a me alienum puto (Nichts Menschliches ist mir fremd)"],
      ["… Motto", "De omnibus dubitandum (An allem ist zu zweifeln)"]
    ]
  },
  {
    "name": "2. Jenny Marx (Jennys Mutter)",
    "baseUrl": "02_Jenny_Marx_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Aufrichtigkeit"],
      ["… beim Mann", "Beharrlichkeit"],
      ["… bei der Frau", "Zuneigung"],
      ["Hauptmerkmal", "Empfindsamkeit"],
      ["Auffassung vom Glück", "Gesundheit"],
      ["… vom Unglück", "Abhängigkeit"],
      ["Das Laster, das Du entschuldigst", "Unentschlossenheit"],
      ["… verabscheust", "Undankbarkeit"],
      ["Abneigung", "Schulden"],
      ["Lieblingsbeschäftigung", "Handarbeit"],
      ["… Dichter", "Goethe"],
      ["… Schriftsteller", "Martin Luther"],
      ["… Held", "Coriolanus"],
      ["… Heldin", "Florence Nightingale"],
      ["… Blume", "Rose"],
      ["… Farbe", "Blau"],
      ["Lieblingsmaxime", "Es ist alles halb so schlimm"],
      ["Motto", "Nil desperandum (Verzweifle nicht)"]
    ]
  },
  {
    "name": "3. Laura Marx (Jennys Schwester)",
    "baseUrl": "03_Laura_Marx_resized",
    "confessions": [
      ["Meine Lieblingstugend", "Wahrhaftigkeit"],
      ["… Eigenschaft beim Mann", "Gerechtigkeit"],
      ["… bei der Frau", "Mitleid"],
      ["Dein Hauptmerkmal", "Unentschlossenheit"],
      ["Deine Auffassung vom Glück", "Die Gewissheit, geliebt zu werden"],
      ["… Unglück", "Selbstgefälligkeit"],
      ["Das Laster, das Du entschuldigst", "In den Tag träumen"],
      ["… verabscheust", "Heuchelei"],
      ["Deine Abneigung", "[Frage nicht beantwortet]"],
      ["Lieblingsbeschäftigung", "Lesen"],
      ["… Dichter", "Shakespeare"],
      ["… Schriftsteller", "Cervantes"],
      ["… Held", "Shelly"],
      ["… Blume", "Rose"],
      ["… Farbe", "Himmelblau"],
      ["… Namen", "Barry, Percy, Edward and Charles"],
      ["… Maxime", "Sich selbst erkennen"],
      ["… Motto", "Magna est veritas et prevalebit (Groß ist die Wahrheit, und sie wird siegen)"]
    ]
  },
  {
    "name": "4. Jenny Marx selbst",
    "baseUrl": "04_Jenny_Marx_resized",
    "confessions": [
      ["Meine Lieblingstugend", "Menschlichkeit"],
      ["… Eigenschaft beim Mann", "Zivilcourage"],
      ["… bei der Frau", "Hingabe"],
      ["Auffassung vom Glück", "Lieben"],
      ["… Unglück", "[unleserlich] "],
      ["Laster, das ich verabscheue", "Neid"],
      ["… entschuldige", "Leichtgläubigkeit"],
      ["Meine Abneigung", "Voreingenommenheit"],
      ["Die historischen Persönlichkeiten, die Du am wenigsten magst", "Buonaparte und seinen Neffen [Napoleon III.]"],
      ["Lieblingsbeschäftigung", ""],
      ["Lieblingsdichter", "Shakespeare"],
      ["… Held", "Gracchus"],
      ["… Blume", "Lilie"],
      ["… Farbe", "Rot"],
      ["… Maxime", "Sei ehrlich zu dir selbst "],
      ["… Motto", "Per aspera ad astra (Durch Mühsal gelangt man zu den Sternen)"]
    ]
  },
  {
    "name": "5. Whiskey (Hund der Familie Marx)",
    "baseUrl": "05-Whiskey_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Bettler anbellen"],
      ["Eigenschaft beim Mann", "Knurrig"],
      ["… bei der Frau", "Bissig"],
      ["Dein Hauptmerkmal", "Hunger"],
      ["Deine Auffassung vom Glück", "Ein Spaziergang nach dem Abendessen"],
      ["… Unglück", "Untergetaucht werden"],
      ["Laster, das Du entschuldigst", "Sich überfressen"],
      ["… verabscheust", "Trunkenheit"],
      ["Deine Lieblingsbeschäftigung", "Knochen nagen"],
      ["… Held", "Odysseus‘ Hund"],
      ["… Heldin", "Noch auf der Suche"],
      ["Schriftsteller", "Buffon [französischer Naturforscher]"],
      ["… Essen", "Fleisch"],
      ["Lieblingsmaxime", "Iss und sei froh"],
      ["… und Motto", "Avec la gêne il n’a pas de plaisir (Hemmungen verhindern das Vergnügen)"]
    ]
  },
  {
    "name": "6. Eleanor Marx (Jennys Schwester)",
    "baseUrl": "06_Eleanor_Marx_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Wahrhaftigkeit"],
      ["… beim Mann", "Mut"],
      ["… bei der Frau", "[Frage nicht beantwortet]"],
      ["Dein Hauptmerkmal", "Neugierde"],
      ["Deine Auffassung vom Glück", "Champagner"],
      ["… vom Unglück", "Die Zahnschmerzen"],
      ["Laster, das Du am meisten entschuldigst", "Die Schule schwänzen "],
      ["…, das Du am meisten verabscheust", "Eves' Prüfung"],
      ["Deine Abneigung", "Kaltes Hammelfleisch"],
      ["Lieblingsbeschäftigung", "Turnen"],
      ["… Dichter", "Shakespeare"],
      ["… Schriftsteller", "Captain Marryat [englischer Jugendbuchautor]"],
      ["… Held", "Garibaldi"],
      ["… Heldin", "Lady Jane Grey [hingerichtete Nichte König Heinrichs VIII.]"],
      ["… Blume", "Alle Blumen"],
      ["… Farbe", "Weiß"],
      ["… Namen", "Percy, Henry, Edward"],
      ["Deine Lieblingsmaxime und Motto", "Immer nach vorn"]
    ]
  },
  {
    "name": "7. Nanette Philips (Jennys Großkusine)",
    "baseUrl": "07_Philipps_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Natürlichkeit"],
      ["… beim Mann", "Mut"],
      ["… bei der Frau", "Feinfühligkeit"],
      ["Dein Hauptmerkmal", "Anpassungsfähigkeit"],
      ["Deine Lieblingsbeschäftigung", "Schlafen!"],
      ["Das Laster, das Du am meisten verabscheust", "Egoismus"],
      ["…, das Du am meisten entschuldigst", "Liebe"],
      ["Deine Abneigung", "Dr. Bloch"],
      ["… Held", "Wilhelm der Schweiger [Statthalter von Holland]"],
      ["… Heldin", "Marie Antoinette"],
      ["Dein Lieblingsdichter", "Goethe"],
      ["… Schriftsteller", "Lessing"],
      ["… Blume", "Die Rose"],
      ["… Essen", "Guter Bordeaux"],
      ["… Maxime", "Fais ce que voudras, arrive ce qui pourra (Tu was du willst, es kommt, wie es kommt)"],
      ["Deine Auffassung vom Glück", "Freiheit"],
      ["Dein Motto", "Vencit vim virtus (Die Tugend bezwingt die Gewalt)"]
    ]
  },
  {
    "name": "8. Caroline Schmalhausen  (Jennys Kusine)",
    "baseUrl": "08_Schmalhausen_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Güte"],
      ["… beim Mann", "Ein starker Wille"],
      ["… bei der Frau", "Weiblichkeit"],
      ["Dein Hauptmerkmal", "Gleichgültigkeit"],
      ["Deine Auffassung vom Glück", "Mit denjenigen, die du liebst, zusammen zu sein "],
      ["… vom Unglück", "In der Liebe betrogen werden"],
      ["Das Laster, das Du am meisten verabscheust", "Heuchelei"],
      ["… … entschuldigst", "Unbesonnenheit"],
      ["Deine Abneigung", "Unentschlossenheit"],
      ["Lieblingsbeschäftigung", "Schlafen"],
      ["Dein derzeitiger Gemütszustand", "Rastlosigkeit"],
      ["Dein Lieblingsdichter", "Bodenstett [deutscher Schriftsteller], Heine"],
      ["… Schriftsteller", "Miss Mulock [englische Schriftstellerin] und Hugo"],
      ["… Held", "Christoph Columbus"],
      ["… Heldin", "[Frage nicht beantwortet]"],
      ["… Blume", "Vanilleblume"],
      ["… Namen", "Edward, Charles, John, Eugene"],
      ["… Essen", "Eis"],
      ["Lieblingsmaxime und Motto", "Sei gerecht"]
    ]
  },
  {
    "name": "9. Caroline Schoeler  (Freundin der Familie Marx)",
    "baseUrl": "09_Schoeler_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Ehrlichkeit"],
      ["… beim Mann", "Zivilcourage"],
      ["… bei der Frau", "Hingabe"],
      ["Dein wichtigster Charakterzug", "Beständigkeit"],
      ["Auffassung vom Glück", "Lieben und geliebt werden"],
      ["… vom Unglück", "Andere verdächtigen"],
      ["Das Laster, das Du entschuldigst", "Extravaganz"],
      ["Das Laster, das Du verabscheust", "Niedertracht"],
      ["Deine Abneigung", "Der Zwiebelgeruch"],
      ["Lieblingsbeschäftigung", "dolce far niente (Süßes Nichtstun)"],
      ["Lieblingsdichter", "Shakespeare"],
      ["… Schriftsteller", "Goethe"],
      ["… Held", "Job [bibl. Gestalt im Alten Testament]"],
      ["… Heldin", "Xantippe [Ehefrau des Sokrates]"],
      ["… Blume", "Wilde Primel"],
      ["… Farbe", "Blau"],
      ["… Essen", "Heiße Suppe"],
      ["… Maxime", "Worte, Worte"],
      ["… Motto", "Pop goes the weasel [Kinderlied, genaue Bedeutung strittig]"]
    ]
  },
  {
    "name": "10. Helene Demuth (Haushälterin der Familie Marx)",
    "baseUrl": "10_Demuth_resized",
    "confessions": [
      ["Ihre Lieblingstugend", "Entschlossenheit"],
      ["… Eigenschaft beim Mann", "Mut"],
      ["… bei der Frau", "Gute Laune"],
      ["Hauptmerkmal", "Die Liebe zu den kleinen Marxens"],
      ["Auffassung vom Glück", "Ein Abendessen essen, das ich nicht zubereitet habe"],
      ["… Unglück", "Von anderen abhängig zu sein"],
      ["Das Laster, das ich entschuldige", "Verschwendung"],
      ["… verabscheu", "Egoismus"],
      ["Deine Abneigung", "Ein Geizhals"],
      ["Die Persönlichkeit, die ich am wenigsten mag", "Lassalle"],
      ["Lieblingsbeschäftigung", "Luftschlösser bauen"],
      ["… Held", "Mein größter Suppentopf"],
      ["… Heldin", "Meine Kaffeekanne"],
      ["… Dichter", "Der, von dem ich am wenigsten kenne"],
      ["… Schriftsteller", "Eugène Sue"],
      ["… Blume", "Rose"],
      ["… Farbe", "Blau"],
      ["… Essen", "Schweinefleisch"],
      ["… Maxime", "Leben und leben lassen!"]
    ]
  },
  {
    "name": "11. Friedrich Engels  (Freund und Förderer der Familie Marx)",
    "baseUrl": "11_Engels_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Fröhlichkeit"],
      ["… Eigenschaft beim Mann", "Sich um seine eignen Angelegenheiten zu kümmern"],
      ["… bei der Frau", "Keine Sachen zu verlegen"],
      ["Hauptmerkmal", "Alles halb zu wissen"],
      ["Auffassung vom Glück", "Château Margaux 1848"],
      ["… Unglück", "Zum Zahnarzt gehen"],
      ["Das Laster, das Du entschuldigst", "Unmäßigkeit aller Art"],
      ["… verabscheust", "Heuchelei"],
      ["Deine Abneigung", "Affektierte, hochnäsige Frauen"],
      ["Die Persönlichkeit, die Sie am wenigsten mögen", "Spurgeon [baptistischer Pfarrer]"],
      ["Lieblingsbeschäftigung", "Necken und geneckt werden"],
      ["… Held", "Keiner"],
      ["… Heldin", "Zu viele, um eine zu nennen"],
      ["… Dichter", "Reineke de Vos, Shakespeare, Ariost etc."],
      ["… Schriftsteller", "Goethe, Lessing, Dr. Samelson [Arzt und Mitglied der Schiller-Anstalt in Manchester]"],
      ["… Blume", "Glockenblume"],
      ["… Farbe", "Alle, bis auf Anilinfarbe"],
      ["… Gericht", "Kalt: Salat, heiß: Irish Stew"],
      ["Die historischen Persönlichkeiten, die Du am wenigsten magst", ""],
      ["… Maxime", "Keine zu haben"],
      ["… Motto", "Immer mit der Ruhe"]
    ]
  },
  {
    "name": "12. Paul Lafargue  (Lauras späterer Ehemann)",
    "baseUrl": "12_Lafargue_resized",
    "confessions": [
      ["Lieblingstugend", "Beobachten und sich in Geduld üben "],
      ["… beim Mann", "Schweigen und abwarten können "],
      ["… bei der Frau", "Koketterie"],
      ["Merkmal", "Zu schnelles Handeln"],
      ["Auffassung vom Glück", "Ein guter Nachtisch"],
      ["… Unglück", "Frieren"],
      ["Laster, das Sie verabscheuen", "Die Tugend"],
      ["… entschuldigen", "Faulheit"],
      ["Lieblingsdichter", "Musset"],
      ["… Schriftsteller", "Rabelais, Pascal, Balzac"],
      ["… Held", "Marat"],
      ["… Heldin", "Kann ich nicht sagen"],
      ["Die Person, die Sie verabscheuen ", "Napoleon I."],
      ["Lieblingsnamen", "Laura, Marguerite"],
      ["… Essen", "Kotelett"],
      ["… Augenfarbe", "Rehbraun"],
      ["… Haarfarbe", "Braun"],
      ["Lieblingsblume", "Moosrose, Veilchen"],
      ["Gemütszustand", "Zufrieden"],
      ["… Namen", ""],
      ["Die historischen Persönlichkeiten, die Du am wenigsten magst", ""],
      ["Maxime", "Überlege dir gut, was du sagst"],
      ["Motto", "Nur der Dumme ändert sich niemals."]
    ]
  },
  {
    "name": "13. Gustave Flourens  (Politiker und Kommunarde)",
    "baseUrl": "13_Flourens_resized",
    "confessions": [
      ["Ihre Lieblingstugend", "Die Kühnheit"],
      ["… Eigenschaft beim Mann", "Die Energie"],
      ["… bei der Frau", "Die Hingabe"],
      ["Auffassung vom Glück", "Als einfacher Bürger in einer egalitären Republik leben"],
      ["… Unglück", "Rechtsanwalt sein"],
      ["Das Laster, das Sie verabscheuen ", "Die Unterwürfigkeit"],
      ["Ihre Abneigung", "Gaukler und Aristokraten"],
      ["Lieblingsbeschäftigung", "Die Großbürger, ihre Götter, ihre Könige und ihre Helden bekämpfen"],
      ["Geschichtliche Persönlichkeiten, die Sie mögen", "Spartacus"],
      ["Lieblingsdichter", "Byron und Les Châtiments [Gedichtsammlung von Hugo]"],
      ["… Prosaautor", "Tacitus"],
      ["… Blume", "Rose"],
      ["… Maxime", "Scire mori (Wissen, wie man stirbt)"],
      ["… Motto", "Гνωθι σεαυτον (Erkenne dich selbst)"],
      ["Ihr Merkmal", "Immer nach vorn"]
    ]
  },
  {
    "name": "14. Prosper-Olivier Lissagaray  (Eleanors Geliebter)",
    "baseUrl": "14_Lissagaray_resized",
    "confessions": [
      ["Deine Lieblingstugend", "Die Liebe"],
      ["… Eigenschaft beim Mann", "Die Liebe"],
      ["… bei der Frau", "Die Liebe"],
      ["Ihr Merkmal", "Lange Nase"],
      ["Auffassung vom Glück", "Dominieren"],
      ["… vom Unglück", "Dominieren"],
      ["Das Laster, das Sie entschuldigen", "Die Eifersucht"],
      ["… verabscheuen", "Die Eifersucht"],
      ["Ihre Abneigung", "Die Lüge"],
      ["Die geschichtlichen Persönlichkeiten, die Sie bewundern", "Caesar"],
      ["… … verabscheuen", "Caesar"],
      ["Lieblingsbeschäftigung", "Rauchen"],
      ["Held", "Elle [Hier handelt es sich offenbar um ein Wortspiel: Das französische „Elle“ entspricht dem Deutschen „Sie“, kann aber auch eine Abkürzung für „Eleanor“ sein.]"],
      ["Heldin", "Elle"],
      ["Dichter", "Elle"],
      ["Schriftsteller", "Elle"],
      ["Augen- und Haarfarbe", "Elle"],
      ["Lieblingsblume", "Rose"],
      ["Lieblingsnamen", "Elle"],
      ["Essen", "0"],
      ["… Motto", "0"]
    ]
  }
]
